from frappe.custom.doctype.custom_field.custom_field import create_custom_fields


def execute():
	custom_fields = {
		"Company": [
			{
				"fieldname": "withholding_tax_section",
				"fieldtype": "Section Break",
				"insert_after": "default_creditors_withholding_account",
				"label": "Withholding Tax",
			},
			{
				"fieldname": "withholding_tax_party_wise",
				"fieldtype": "Check",
				"insert_after": "withholding_tax_section",
				"label": "Withholding TAX Party Wise",
				"default": "",
			},
			{
				"fieldname": "withholding_tax_no_party",
				"fieldtype": "Check",
				"insert_after": "withholding_tax_party_wise",
				"label": "Withholding TAX No Party",
				"default": "",
			},
			{
				"fieldname": "withholding_tax_party_accounts_section",
				"fieldtype": "Section Break",
				"insert_after": "withholding_tax_no_party",
				"label": "Party Wise Accounts",
				"depends_on": "eval:doc.withholding_tax_party_wise",
			},
			{
				"fieldname": "withholding_tax_party_wise_payable_account",
				"fieldtype": "Link",
				"insert_after": "withholding_tax_party_accounts_section",
				"label": "Purchase Withholding Tax Account (Party Wise)",
				"options": "Account",
				"depends_on": "eval:doc.withholding_tax_party_wise",
			},
			{
				"fieldname": "withholding_tax_party_wise_column_break",
				"fieldtype": "Column Break",
				"insert_after": "withholding_tax_party_wise_payable_account",
			},
			{
				"fieldname": "withholding_tax_party_wise_receivable_account",
				"fieldtype": "Link",
				"insert_after": "withholding_tax_party_wise_column_break",
				"label": "Sales Withholding Tax Account (Party Wise)",
				"options": "Account",
				"depends_on": "eval:doc.withholding_tax_party_wise",
			},
			{
				"fieldname": "withholding_tax_no_party_section",
				"fieldtype": "Section Break",
				"insert_after": "withholding_tax_party_wise_receivable_account",
				"label": "No Party Accounts",
				"depends_on": "eval:doc.withholding_tax_no_party",
			},
			{
				"fieldname": "withholding_tax_no_party_payable_account",
				"fieldtype": "Link",
				"insert_after": "withholding_tax_no_party_section",
				"label": "Purchase Withholding Tax Account (No Party)",
				"options": "Account",
				"depends_on": "eval:doc.withholding_tax_no_party",
			},
			{
				"fieldname": "withholding_tax_no_party_column_break",
				"fieldtype": "Column Break",
				"insert_after": "withholding_tax_no_party_payable_account",
			},
			{
				"fieldname": "withholding_tax_no_party_receivable_account",
				"fieldtype": "Link",
				"insert_after": "withholding_tax_no_party_column_break",
				"label": "Sales Withholding Tax Account (No Party)",
				"options": "Account",
				"depends_on": "eval:doc.withholding_tax_no_party",
			},
			{
				"fieldname": "withholding_vat_section",
				"fieldtype": "Section Break",
				"insert_after": "withholding_tax_no_party_receivable_account",
				"label": "Withholding VAT",
			},
			{
				"fieldname": "withholding_vat_party_wise",
				"fieldtype": "Check",
				"insert_after": "withholding_vat_section",
				"label": "Withholding VAT Party Wise",
				"default": "",
			},
			{
				"fieldname": "withholding_vat_no_party",
				"fieldtype": "Check",
				"insert_after": "withholding_vat_party_wise",
				"label": "Withholding VAT No Party",
				"default": "",
			},
			{
				"fieldname": "withholding_vat_party_accounts_section",
				"fieldtype": "Section Break",
				"insert_after": "withholding_vat_no_party",
				"label": "Party Wise Accounts",
				"depends_on": "eval:doc.withholding_vat_party_wise",
			},
			{
				"fieldname": "withholding_vat_party_wise_payable_account",
				"fieldtype": "Link",
				"insert_after": "withholding_vat_party_accounts_section",
				"label": "Purchase Withholding VAT Account (Party Wise)",
				"options": "Account",
				"depends_on": "eval:doc.withholding_vat_party_wise",
			},
			{
				"fieldname": "withholding_vat_party_wise_column_break",
				"fieldtype": "Column Break",
				"insert_after": "withholding_vat_party_wise_payable_account",
			},
			{
				"fieldname": "withholding_vat_party_wise_receivable_account",
				"fieldtype": "Link",
				"insert_after": "withholding_vat_party_wise_column_break",
				"label": "Sales Withholding VAT Account (Party Wise)",
				"options": "Account",
				"depends_on": "eval:doc.withholding_vat_party_wise",
			},
			{
				"fieldname": "withholding_vat_no_party_section",
				"fieldtype": "Section Break",
				"insert_after": "withholding_vat_party_wise_receivable_account",
				"label": "No Party Accounts",
				"depends_on": "eval:doc.withholding_vat_no_party",
			},
			{
				"fieldname": "withholding_vat_no_party_payable_account",
				"fieldtype": "Link",
				"insert_after": "withholding_vat_no_party_section",
				"label": "Purchase Withholding VAT Account (No Party)",
				"options": "Account",
				"depends_on": "eval:doc.withholding_vat_no_party",
			},
			{
				"fieldname": "withholding_vat_no_party_column_break",
				"fieldtype": "Column Break",
				"insert_after": "withholding_vat_no_party_payable_account",
			},
			{
				"fieldname": "withholding_vat_no_party_receivable_account",
				"fieldtype": "Link",
				"insert_after": "withholding_vat_no_party_column_break",
				"label": "Sales Withholding VAT Account (No Party)",
				"options": "Account",
				"depends_on": "eval:doc.withholding_vat_no_party",
			},
			{
				"fieldname": "enable_purchase_withholding_section",
				"fieldtype": "Section Break",
				"insert_after": "withholding_vat_no_party_receivable_account",
				"label": "Automation",
			},
			{
				"fieldname": "auto_create_purchase_withholding_je",
				"fieldtype": "Check",
				"insert_after": "enable_purchase_withholding_section",
				"label": "Auto Create Purchase Withholding JE",
				"default": "",
			},
			{
				"fieldname": "auto_submit_purchase_withholding_je",
				"fieldtype": "Check",
				"insert_after": "auto_create_purchase_withholding_je",
				"label": "Auto Submit Purchase Withholding JE",
				"default": "",
			},
			{
				"fieldname": "withholding_auto_column_break",
				"fieldtype": "Column Break",
				"insert_after": "auto_submit_purchase_withholding_je",
			},
			{
				"fieldname": "auto_create_sales_withholding_je",
				"fieldtype": "Check",
				"insert_after": "withholding_auto_column_break",
				"label": "Auto Create Sales Withholding JE",
				"default": "",
			},
			{
				"fieldname": "auto_submit_sales_withholding_je",
				"fieldtype": "Check",
				"insert_after": "auto_create_sales_withholding_je",
				"label": "Auto Submit Sales Withholding JE",
				"default": "",
			},
		],
		"Item": [
			{
				"fieldname": "withholding_tax_rate_on_purchase",
				"fieldtype": "Percent",
				"insert_after": "stock_uom",
				"label": "Withholding Tax Rate on Purchase",
			},
			{
				"fieldname": "withholding_tax_rate_on_sales",
				"fieldtype": "Percent",
				"insert_after": "withholding_tax_rate_on_purchase",
				"label": "Withholding Tax Rate on Sales",
			},
		],
		"Customer": [
			{
				"fieldname": "withholding_vat_rate",
				"fieldtype": "Percent",
				"insert_after": "tax_id",
				"label": "Withholding VAT Rate",
			},
		],
		"Supplier": [
			{
				"fieldname": "withholding_vat_rate",
				"fieldtype": "Percent",
				"insert_after": "tax_id",
				"label": "Withholding VAT Rate",
			},
		],
		"Purchase Invoice Item": [
			{
				"fieldname": "withholding_tax_rate",
				"fieldtype": "Percent",
				"insert_after": "item_tax_template",
				"label": "Withholding Tax Rate",
				"fetch_from": "item_code.withholding_tax_rate_on_purchase",
				"fetch_if_empty": 1,
				"allow_on_submit": 1,
				"no_copy": 1,
			},
			{
				"fieldname": "withholding_tax_amount",
				"fieldtype": "Currency",
				"insert_after": "withholding_tax_rate",
				"label": "Withholding Tax Amount",
				"read_only": 1,
				"allow_on_submit": 1,
				"no_copy": 1,
			},
			{
				"fieldname": "withholding_tax_entry",
				"fieldtype": "Link",
				"insert_after": "withholding_tax_amount",
				"label": "Withholding Tax Entry",
				"options": "Journal Entry",
				"read_only": 1,
				"allow_on_submit": 1,
				"no_copy": 1,
			},
			{
				"fieldname": "csf_ke_wtax_je_created",
				"fieldtype": "Check",
				"insert_after": "withholding_tax_entry",
				"label": "CSF KE Wtax JE Created",
				"read_only": 1,
				"allow_on_submit": 1,
				"no_copy": 1,
				"default": "0",
			},
		],
		"Sales Invoice Item": [
			{
				"fieldname": "withholding_tax_rate",
				"fieldtype": "Percent",
				"insert_after": "item_tax_template",
				"label": "Withholding Tax Rate",
				"fetch_from": "item_code.withholding_tax_rate_on_sales",
				"fetch_if_empty": 1,
				"allow_on_submit": 1,
				"no_copy": 1,
			},
			{
				"fieldname": "withholding_tax_amount",
				"fieldtype": "Currency",
				"insert_after": "withholding_tax_rate",
				"label": "Withholding Tax Amount",
				"read_only": 1,
				"allow_on_submit": 1,
				"no_copy": 1,
			},
			{
				"fieldname": "withholding_tax_entry",
				"fieldtype": "Link",
				"insert_after": "withholding_tax_amount",
				"label": "Withholding Tax Entry",
				"options": "Journal Entry",
				"read_only": 1,
				"allow_on_submit": 1,
				"no_copy": 1,
			},
			{
				"fieldname": "csf_ke_wtax_je_created",
				"fieldtype": "Check",
				"insert_after": "withholding_tax_entry",
				"label": "CSF KE Wtax JE Created",
				"read_only": 1,
				"allow_on_submit": 1,
				"no_copy": 1,
				"default": "0",
			},
		],
		"Purchase Invoice": [
			{
				"fieldname": "withholding_vat_rate",
				"fieldtype": "Percent",
				"insert_after": "is_filed",
				"label": "Withholding VAT Rate",
				"allow_on_submit": 1,
				"no_copy": 1,
			},
			{
				"fieldname": "withholding_vat_amount",
				"fieldtype": "Currency",
				"insert_after": "withholding_vat_rate",
				"label": "Withholding VAT Amount",
				"read_only": 1,
				"allow_on_submit": 1,
				"no_copy": 1,
			},
			{
				"fieldname": "withholding_vat_entry",
				"fieldtype": "Link",
				"insert_after": "withholding_vat_amount",
				"label": "Withholding VAT Entry",
				"options": "Journal Entry",
				"read_only": 1,
				"allow_on_submit": 1,
				"no_copy": 1,
			},
			{
				"fieldname": "csf_ke_wvat_je_created",
				"fieldtype": "Check",
				"insert_after": "withholding_vat_entry",
				"label": "CSF KE Wvat JE Created",
				"read_only": 1,
				"allow_on_submit": 1,
				"no_copy": 1,
				"default": "0",
			},
		],
		"Sales Invoice": [
			{
				"fieldname": "withholding_vat_rate",
				"fieldtype": "Percent",
				"insert_after": "is_filed",
				"label": "Withholding VAT Rate",
				"allow_on_submit": 1,
				"no_copy": 1,
			},
			{
				"fieldname": "withholding_vat_amount",
				"fieldtype": "Currency",
				"insert_after": "withholding_vat_rate",
				"label": "Withholding VAT Amount",
				"read_only": 1,
				"allow_on_submit": 1,
				"no_copy": 1,
			},
			{
				"fieldname": "withholding_vat_entry",
				"fieldtype": "Link",
				"insert_after": "withholding_vat_amount",
				"label": "Withholding VAT Entry",
				"options": "Journal Entry",
				"read_only": 1,
				"allow_on_submit": 1,
				"no_copy": 1,
			},
			{
				"fieldname": "csf_ke_wvat_je_created",
				"fieldtype": "Check",
				"insert_after": "withholding_vat_entry",
				"label": "CSF KE Wvat JE Created",
				"read_only": 1,
				"allow_on_submit": 1,
				"no_copy": 1,
				"default": "0",
			},
		],
	}

	create_custom_fields(custom_fields, update=True)
